// HTML export — turn a saved session into a single, self-contained,
// shareable HTML document. No external assets, no scripts, inline CSS only,
// so the file works offline, opens in any browser, and can be emailed or
// committed as an artifact. Pure over a SessionRecord.
//
// This is the "polished artifact" that hosted research tools produce and the
// terminal markdown doesn't: the thing you hand to a colleague. The answer's
// markdown is rendered via the hand-rolled src/markdown.ts so there's still
// zero runtime dependency.

import type { SessionRecord } from "./sessions.js";
import { markdownToHtml, escapeHtml } from "./markdown.js";

const CITATION_ANCHOR_PREFIX = "source-";

export interface HtmlReportOptions {
  // Footer credit line. Defaults to the deepdive/Sprayberry Labs credit.
  // Pass "" to suppress it entirely.
  footer?: string;
}

const DEFAULT_FOOTER =
  'Generated by <a href="https://github.com/askalf/deepdive" rel="noopener noreferrer">deepdive</a>' +
  ' — a local research agent from <a href="https://sprayberrylabs.com" rel="noopener noreferrer">Sprayberry Labs</a>.';

export function renderHtmlReport(
  record: SessionRecord,
  opts: HtmlReportOptions = {},
): string {
  const title = escapeHtml(oneLine(record.question)) || "deepdive report";
  const body = markdownToHtml(record.answer, {
    citationAnchorPrefix: CITATION_ANCHOR_PREFIX,
  });
  const meta = renderMetaLine(record);
  const sources = renderSourcesHtml(record);
  const footer =
    opts.footer === undefined ? DEFAULT_FOOTER : opts.footer;
  const footerHtml = footer ? `\n  <footer>${footer}</footer>` : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="deepdive">
<title>${title}</title>
<style>${STYLE}</style>
</head>
<body>
<main>
  <h1>${title}</h1>
  ${meta}
  <article>
${body}
  </article>
${sources}${footerHtml}
</main>
</body>
</html>
`;
}

function renderMetaLine(record: SessionRecord): string {
  const parts: string[] = [];
  const created = new Date(record.createdAt);
  if (!Number.isNaN(created.getTime())) {
    parts.push(`<time datetime="${created.toISOString()}">${created.toISOString().slice(0, 10)}</time>`);
  }
  if (record.llm?.model) parts.push(escapeHtml(record.llm.model));
  const n = record.sources.length;
  parts.push(`${n} source${n === 1 ? "" : "s"}`);
  if (record.rounds.length > 0) {
    parts.push(`${record.rounds.length} round${record.rounds.length === 1 ? "" : "s"}`);
  }
  const cost = record.cost?.amountUsd;
  if (typeof cost === "number" && Number.isFinite(cost) && cost > 0) {
    parts.push(`~$${cost.toFixed(cost < 0.01 ? 4 : 2)}`);
  }
  return `<p class="meta">${parts.join(" &middot; ")}</p>`;
}

function renderSourcesHtml(record: SessionRecord): string {
  if (record.sources.length === 0) return "";
  const items = record.sources
    .map((s) => {
      const date = new Date(s.fetchedAt);
      const dateStr = Number.isNaN(date.getTime())
        ? ""
        : ` <span class="fetched">fetched ${date.toISOString().slice(0, 10)}</span>`;
      const safeUrl = escapeHtml(s.url);
      const label = escapeHtml(oneLine(s.title)) || safeUrl;
      const safeHref = isSafeHref(s.url) ? safeUrl : "#";
      return `    <li id="${CITATION_ANCHOR_PREFIX}${s.id}"><a href="${safeHref}" rel="noopener noreferrer">${label}</a>${dateStr}</li>`;
    })
    .join("\n");
  return `  <section class="sources">\n    <h2>Sources</h2>\n    <ol>\n${items}\n    </ol>\n  </section>`;
}

function isSafeHref(url: string): boolean {
  return /^(https?:|mailto:|file:)/i.test(url);
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

// Inline stylesheet — readable typography, light/dark aware, print-friendly.
const STYLE = `
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body {
  margin: 0;
  font: 16px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  color: #1a1a1a;
  background: #fbfbfa;
}
main { max-width: 46rem; margin: 0 auto; padding: 3rem 1.25rem 4rem; }
h1 { font-size: 1.85rem; line-height: 1.25; margin: 0 0 0.5rem; letter-spacing: -0.01em; }
h2 { font-size: 1.3rem; margin: 2rem 0 0.75rem; }
h3 { font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
h4, h5, h6 { margin: 1.25rem 0 0.5rem; }
p { margin: 0 0 1rem; }
a { color: #1a56db; text-decoration: none; }
a:hover { text-decoration: underline; }
.meta { color: #6b7280; font-size: 0.85rem; margin: 0 0 2rem; }
article { font-size: 1.02rem; }
ul, ol { padding-left: 1.5rem; margin: 0 0 1rem; }
li { margin: 0.3rem 0; }
blockquote { margin: 0 0 1rem; padding: 0.4rem 1rem; border-left: 3px solid #d1d5db; color: #4b5563; }
code { font: 0.88em ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace; background: #f0f0ef; padding: 0.1em 0.35em; border-radius: 4px; }
pre { background: #f0f0ef; padding: 1rem; border-radius: 8px; overflow-x: auto; margin: 0 0 1rem; }
pre code { background: none; padding: 0; }
table { border-collapse: collapse; width: 100%; margin: 0 0 1.25rem; font-size: 0.95rem; }
th, td { border: 1px solid #e5e7eb; padding: 0.5rem 0.7rem; text-align: left; vertical-align: top; }
th { background: #f3f4f6; font-weight: 600; }
hr { border: none; border-top: 1px solid #e5e7eb; margin: 2rem 0; }
sup.cite { font-size: 0.7em; line-height: 0; }
sup.cite a { padding: 0 0.1em; }
.sources { margin-top: 2.5rem; border-top: 1px solid #e5e7eb; padding-top: 1rem; }
.sources li { margin: 0.45rem 0; }
.sources .fetched { color: #9ca3af; font-size: 0.82rem; }
:target { background: #fff3bf; scroll-margin-top: 1rem; }
footer { margin-top: 3rem; padding-top: 1.25rem; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.82rem; }
@media (prefers-color-scheme: dark) {
  body { color: #e5e7eb; background: #18181b; }
  a { color: #7aa7ff; }
  .meta, footer { color: #9ca3af; }
  blockquote { border-left-color: #3f3f46; color: #a1a1aa; }
  code, pre { background: #27272a; }
  th { background: #27272a; }
  th, td { border-color: #3f3f46; }
  hr, .sources, footer { border-color: #3f3f46; }
  :target { background: #422006; }
}
@media print {
  body { background: #fff; }
  main { max-width: none; padding: 0; }
  a { color: inherit; }
}
`.trim();
